Removed comma's, reduced timeout.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -198,18 +198,18 @@ jobs:
         id: cucumber_job
         continue-on-error: true
         run: |
-          if ! kubectl wait --for=condition=complete --all jobs --timeout=30m; then
-            echo "::error::Kubectl timed out...";
-            echo "status=ERROR" >> $GITHUB_OUTPUT;
+          if ! kubectl wait --for=condition=complete --all jobs --timeout=1m; then
+            echo "::error::Kubectl timed out..."
+            echo "status=ERROR" >> $GITHUB_OUTPUT
             kubectl get events --all-namespaces  --sort-by='.metadata.creationTimestamp' &> kube_events.log
             for pod in $(kubectl get pod --field-selector=status.phase==Running -o name); do 
-              echo "::debug:: Created logs for pod $pod";
-              kubectl logs $pod --all-containers=true &> ${pod}.log ;
+              echo "::debug:: Created logs for pod $pod"
+              kubectl logs $pod --all-containers=true &> ${pod}.log
             done; 
-            kubectl get pods &> kube_status.log;
+            kubectl get pods &> kube_status.log
             exit 1
           fi;
-          echo "status=SUCCES" >> $GITHUB_OUTPUT;
+          echo "status=SUCCES" >> $GITHUB_OUTPUT
       - name: Upload error logs
         uses: actions/upload-artifact@v4
         with:
