Try to fix cucumber job output.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -198,7 +198,7 @@ jobs:
         id: cucumber_job
         continue-on-error: true
         run: |
-          if ! kubectl wait --for=condition=complete --all jobs --timeout=30m; then
+          if ! kubectl wait --for=condition=complete --all jobs --timeout=10s; then
             echo "::error::Kubectl timed out...";
             kubectl get events --all-namespaces  --sort-by='.metadata.creationTimestamp' 2> kube_events.log
             for pod in $(kubectl get pod --field-selector=status.phase==Running -o name); do 
@@ -206,7 +206,8 @@ jobs:
               kubectl logs $pod --all-containers=true 2> ${pod}.log ;
             done; 
             kubectl get pods 2> kube_status.log;
-            echo "status=ERROR" >> $GITHUB_OUTPUT;
+            echo "status='ERROR'" >> $GITHUB_OUTPUT;
+	    exit 1
           fi;
           echo "status=SUCCES" >> $GITHUB_OUTPUT;
       - name: Upload error logs
